- name: Add apt-key
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present
  become: true

- name: Set up apt repo for grafana
  apt_repository:
    repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
    state: present
  become: true

- name: check grafana_state var
  assert:
    that:
      - grafana_state == "present" or grafana_state == "latest"
    msg: "grafana_state must be 'present' or 'latest'"
  become: true

- name: Install grafana
  when: grafana_state == "present"
  apt:
    name: grafana
    update_cache: yes
    state: present
  become: true

- name: Updated grafana
  when: grafana_state == "latest"
  apt:
    name: grafana
    update_cache: yes
    state: latest
  become: true
  notify:
    - restart grafana

- name: Install sqlite3
  apt:
    name: sqlite3
    update_cache: yes
  become: true

- name: Copy out the grafana config
  copy:
    src: "{{ grafana_ini_file }}"
    dest: /etc/grafana/grafana.ini
    mode: 0640
  become: true
  notify:
    - reload systemd
    - restart grafana

- name: Enable grafana
  systemd:
    enabled: yes
    name: grafana-server
  become: true
