---

- name: setup yarn apt repo
  apt_repository:
    repo: "ppa:timescale/timescaledb-ppa"
    state: present
  become: true

- name: Install timescaledb
  apt:
    name:
      - timescaledb-postgresql-10
    state: present
    update_cache: yes
  become: true

- name: Check if pg_prometheus is installed
  shell: test -f /usr/lib/postgresql/10/lib/pg_prometheus.so
  ignore_errors: yes
  register: pg_prometheus_installed
  tags: pg_prometheus
  changed_when: false

- name: Install requirements for pg_prometheus
  apt:
    name:
      - cmake
      - libpq-dev
    state: present
    update_cache: yes
  become: true

- name: Clone pg_prometheus repo
  git:
    repo: "https://github.com/timescale/pg_prometheus.git"
    dest: /opt/pg_prometheus
    clone: yes
  when: pg_prometheus_installed is failed
  become: true

- name: Make pg_prometheus
  make:
    chdir: /opt/pg_prometheus
  when: pg_prometheus_installed is failed
  become: yes

- name: Make install pg_prometheus
  make:
    chdir: /opt/pg_prometheus
    target: install
  when: pg_prometheus_installed is failed
  become: yes

- name: restart postgres
  service:
    name: postgresql
    state: restarted
  become: true

- name: set up timescale db extension
  postgresql_ext:
    db: "{{ prometheus_postgresql_database }}"
    name: timescaledb
  become: true

- name: set up pg_prometheus db extension
  postgresql_ext:
    db: "{{ prometheus_postgresql_database }}"
    name: pg_prometheus
  become: true

- name: "Create version folder"
  file:
    path: "/home/prometheus/pg_adapter/{{ prometheus_postgres_adapter_version }}"
    state: directory
    mode: 0700
  become: yes
  become_user: prometheus

- name: "Download the adapter file"
  get_url:
    url: "https://github.com/timescale/prometheus-postgresql-adapter/releases/download/{{ prometheus_postgres_adapter_version }}/prometheus-postgresql-adapter-{{ prometheus_postgres_adapter_version }}-linux-amd64.tar.gz"
    dest: "/home/prometheus/pg_adapter/{{ prometheus_postgres_adapter_version }}/pg_adapter.tar.gz"
    mode: 0400
    checksum: "sha256:{{ prometheus_postgres_adapter_checksum }}"
  become: yes
  become_user: prometheus

- name: stat extracted folder
  stat: path="/home/prometheus/pg_adapter/{{ prometheus_version }}/prometheus-postgres-adapter"
  register: prometheus_pg_adapter_extracted_folder_stat
  become: yes
  become_user: prometheus

- name: "Extract archive"
  unarchive:
    src: "/home/prometheus/pg_adapter/{{ prometheus_postgres_adapter_version }}/pg_adapter.tar.gz"
    dest: "/home/prometheus/pg_adapter/{{ prometheus_postgres_adapter_version }}/"
    remote_src: yes
  when: prometheus_pg_adapter_extracted_folder_stat.stat.exists == False
  become: yes
  become_user: prometheus

- name: Template out the service file
  template:
    src: prometheus-postgres-adapter.service.j2
    dest: /etc/systemd/system/prometheus-postgres-adapter.service
    mode: 0644
  become: yes
  notify:
    - reload systemd
    - restart prometheus-postgres-adapter

- name: Enable prometheus-postgres-adapter
  systemd:
    enabled: yes
    name: prometheus-postgres-adapter
  become: yes
