---

- name: Install dependencies for timescaledb
  apt:
    name:
      - cmake
      - postgresql-server-dev-10
    state: present
    update_cache: yes
  become: true

- name: Check if timescaledb is installed
  shell: test -f /usr/lib/postgresql/10/lib/timescaledb.so
  ignore_errors: yes
  register: timescaledb_installed
  tags: timescaledb
  changed_when: false

- name: Clone timescaledb repo
  git:
    repo: "https://github.com/timescale/timescaledb.git"
    dest: /opt/timescaledb
    clone: yes
  when: timescaledb_installed | failed
  become: true

- name: Bootstrap timescaledb
  shell: rm -rf build/ && ./bootstrap
  args:
    chdir: /opt/timescaledb
  when: timescaledb_installed | failed
  become: true

- name: Make timescaledb
  make:
    chdir: /opt/timescaledb/build
  when: timescaledb_installed | failed
  become: yes

- name: Make install timescaledb
  make:
    chdir: /opt/timescaledb/build
    target: install
  when: timescaledb_installed | failed
  become: yes
  notify:
    - restart postgres

- name: Check if pg_prometheus is installed
  shell: test -f /usr/lib/postgresql/10/lib/pg_prometheus.so
  ignore_errors: yes
  register: pg_prometheus_installed
  tags: pg_prometheus
  changed_when: false

- name: Clone pg_prometheus repo
  git:
    repo: "https://github.com/timescale/pg_prometheus.git"
    dest: /opt/pg_prometheus
    clone: yes
  when: pg_prometheus_installed | failed
  become: true

- name: Make pg_prometheus
  make:
    chdir: /opt/pg_prometheus
  when: pg_prometheus_installed | failed
  become: yes

- name: Make install pg_prometheus
  make:
    chdir: /opt/pg_prometheus
    target: install
  when: pg_prometheus_installed | failed
  become: yes

- name: "Create version folder"
  file:
    path: "/home/prometheus/pg_adapter/{{ prometheus_postgres_adapter_version }}"
    state: directory
    mode: 0700
  become: yes
  become_user: prometheus

- name: "Download the adapter file"
  get_url:
    url: "https://github.com/timescale/prometheus-postgresql-adapter/releases/download/{{ prometheus_postgres_adapter_version }}/prometheus-postgresql-adapter-{{ prometheus_postgres_adapter_version }}-linux-amd64.tar.gz"
    dest: "/home/prometheus/pg_adapter/{{ prometheus_postgres_adapter_version }}/pg_adapter.tar.gz"
    mode: 0400
    checksum: "sha256:{{ prometheus_postgres_adapter_checksum }}"
  become: yes
  become_user: prometheus

- name: stat extracted folder
  stat: path="/home/prometheus/pg_adapter/{{ prometheus_version }}/prometheus-postgres-adapter"
  register: prometheus_pg_adapter_extracted_folder_stat
  become: yes
  become_user: prometheus

- name: "Extract archive"
  unarchive:
    src: "/home/prometheus/pg_adapter/{{ prometheus_postgres_adapter_version }}/pg_adapter.tar.gz"
    dest: "/home/prometheus/pg_adapter/{{ prometheus_postgres_adapter_version }}/"
    remote_src: yes
  when: prometheus_pg_adapter_extracted_folder_stat.stat.exists == False
  become: yes
  become_user: prometheus

- name: Template out the service file
  template:
    src: prometheus-postgres-adapter.service.j2
    dest: /etc/systemd/system/prometheus-postgres-adapter.service
    mode: 0644
  become: yes
  notify:
    - reload systemd
    - restart prometheus-postgres-adapter

- name: Enable prometheus-postgres-adapter
  systemd:
    enabled: yes
    name: prometheus-postgres-adapter
  become: yes
