---
- name: reload systemd
  command: systemctl daemon-reload
  become: true

- name: restart prometheus
  service:
    name: prometheus
    state: restarted
  become: true

- name: restart grafana
  service:
    name: grafana-server
    state: restarted
  become: true

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted
  when: alertmanager_enabled == True
  become: true

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted
  become: true

- name: restart redis_exporter
  service:
    name: redis_exporter
    state: restarted
  become: true

- name: restart postgres_exporter
  service:
    name: postgres_exporter
    state: restarted
  become: true
