---
- name: reload systemd
  command: systemctl daemon-reload
  become: true

- name: restart prometheus
  service:
    name: prometheus
    state: restarted
  become: true

- name: restart grafana
  service:
    name: grafana-server
    state: restarted
  become: true

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted
  when: alertmanager_enabled == True
  become: true

- name: restart prometheus-postgres-adapter
  service:
    name: prometheus-postgres-adapter
    state: restarted
  become: true

- name: restart postgres
  service:
    name: postgresql
    state: restarted
  become: true
